### ISSUE TITLE
feat: add connection pool

### ISSUE THREAD

**Issue by NassiHarel** [NodeRedis/node-redis#1184]
What about creating redis connection pool ?

**Comment by dguo** [comment]
Last year, #226 was labeled as a `wontfix`.

**Comment by nileshsride** [comment]
This is a must needed feature.

**Comment by arendjr** [comment]
+1: In relation to #329 I agree it would be nice if node_redis could handle such use cases out of the box without everyone having to implement their own connection pool.

**Comment by antolovich** [comment]
+1

**Comment by funny-falcon-at-joomcode** [comment]
https://redis.io/topics/transactions
> Redis scripting and transactions
> A Redis script is transactional by definition, so everything you can do with a Redis transaction, you can also do with a script, and usually the script will be both simpler and faster.
