### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by CruiseMan** [NodeRedis/node-redis#1402]
Since last update on https://www.npmjs.com/package/redis this library got many more comments and PR merged do you have plans to update npm package ?.
What is the status on this ?.

**Comment by MohammedFadin** [comment]
No update on this?

**Comment by thatguydan** [comment]
+1

**Comment by knoxcard** [comment]
@bengl

**Comment by BridgeAR** [comment]
I would need someone who sponsors my work to properly continue working on node_redis. I would love to do that but so far this is my main constraint to continue everything. It is just very time consuming. If there's anyone who would be willing to sponsor me, that would be great! I am happy not only to continue supporting everything depending on the sponsoring but also to implement new features.

**Comment by knoxcard** [comment]
@BridgeAR - ok completely understood, but the only extra work being requested here is changing one line of code.  I'll submit the pull request right now.  I am seeing a lot of popular repositories responding with the same answers.

**Comment by pzrq** [comment]
@BridgeAR Could `npm fund` at least help get the word out (though it looks like it would require at least one new release)?
https://dev.to/ruyadorno/npm-6-13-0-7f3

**Comment by Salakar** [comment]
Have started a conversation here about this: https://github.com/NodeRedis/node_redis/issues/1040#issuecomment-581418899

**Comment by Salakar** [comment]
Hey, v3.0.0 is now published to NPM; https://github.com/NodeRedis/node-redis/releases/tag/v3.0.0
