### ISSUE TITLE
https://redis.js.org/ does not work

### ISSUE THREAD

**Issue by vithmel** [NodeRedis/node-redis#1443]
![3333333333333](https://user-images.githubusercontent.com/15888026/58814296-36f2a500-862e-11e9-86b9-2b5847268b14.png)
![4444444](https://user-images.githubusercontent.com/15888026/58814331-407c0d00-862e-11e9-92f2-0e8c6da4fb6f.png)

**Comment by AmirAlOmari** [comment]
+1

**Comment by danielsss** [comment]
+1

**Comment by stockholmux** [comment]
@BridgeAR Do you have the ability to make this change? I do not.

**Comment by Salakar** [comment]
I'll get this sorted soon, thanks for the report

**Comment by Salakar** [comment]
I've fixed this and its now live. Thank you
