### ISSUE TITLE
NPM release?

### ISSUE THREAD

**Issue by mmkal** [NodeRedis/node-redis#1484]
I notice that there hasn't been a release in more than two years on https://npmjs.com/package/redis - is that intentional? [This recent issue](https://github.com/NodeRedis/node_redis/issues/1476) was closed with the response that the library is still active, so maybe there's something missing in the docs.

For example, [this PR](https://github.com/NodeRedis/node_redis/pull/1425) was merged in 2019 but there's no release for it on npm. Should we be installing with something like `npm install NodeRedis/node_redis` to get from github directly? Or should we do something else, like install `redis-commands` separately? If so, can the right process be documented?

**Comment by davalapar** [comment]
Related https://github.com/NodeRedis/node-redis-parser/issues/54

**Comment by Salakar** [comment]
I started a conversation on this over at : https://github.com/NodeRedis/node_redis/issues/1040#issuecomment-581418899

**Comment by Salakar** [comment]
Hey, v3.0.0 is now published to NPM; https://github.com/NodeRedis/node-redis/releases/tag/v3.0.0
