### ISSUE TITLE
URL not working.

### ISSUE THREAD

**Issue by supertiger1234** [NodeRedis/node-redis#1501]
### Issue

```
import { RedisClient } from 'redis'
new RedisClient({
      url: "redis://rediscloud:pass@redis-ttt.ttt.eu-central-1-1.ec2.cloud.redislabs.com:13180"
});
```
Why is this not working? It's giving me this error: `Error: Redis connection to 127.0.0.1:6379 failed`

---

### Environment

 - **Node.js Version**: `v12.14.1`
 

 - **Redis Version**: `4.0.9`
 

 - **Platform**: Windows 10 & Ubuntu

**Comment by stockholmux** [comment]
@supertiger1234 instead of `new RedisClient` you should use `redis.createClient`

**Comment by supertiger1234** [comment]
> @supertiger1234 instead of `new RedisClient` you should use `redis.createClient`

I'm using typescript, so i did `import { RedisClient } from 'redis'`. (I also tried in normal nodejs, and it still doesn't work). I found a new way though by just providing the host, username and password. I still hoped the url to work.

**Comment by designfrontier** [comment]
This appears to still not be working how it is described in the docs. Both passing a redis url as a string to `createClient('redis://redis-host:6379/0')` and passing it in the config object as value for the url key. Both seem to append 127.0.0.1 to the url making it invalid.

**Comment by Deekor** [comment]
Can confirm -  still broken

**Comment by andrewcharnley** [comment]
Still broken in 3.1.2

**Comment by pawan-bobbili-nutanix** [comment]
> Still broken in 3.1.2

Got any solution @andrewcharnley ?

**Comment by andrewcharnley** [comment]
In my case it was to do with the newer rediscloud:pass syntax which is Redis v6, on earlier version it fails.

**Comment by mohammed-hakim** [comment]
what should i do to getthe server working ??

**Comment by dayvsonsales** [comment]
@andrewcharnley have you found another lib that works with this kind of URL? I'm having the same problem here.

**Comment by pawan-bobbili-nutanix** [comment]
@dayvsonsales 
In my case, was using a dummy username,  mostly `h`, removing the username portion for redisURL solved the issue for me

**Comment by dayvsonsales** [comment]
@pawan-bobbili-nutanix I didn't get it. Could you give an example, please?

**Comment by pawan-bobbili-nutanix** [comment]
@dayvsonsales 
syntax for redis URL is like `[redis[s]:]//[[user][:password@]][host][:port][/db-number][?db=db-number[&password=bar[&option=value]]]` right, when upgraded to 3.1.1, my redis connection was failing, on searching , found that the issue i placed the dummy username in the user place of syntax. So, I removed it.

Previously (Not working after updated to 3.1.1)
`redis://h:{rest of the url}`
Now (Working in 3.1.1)
`redis://:{rest of the url}`

**Comment by pulzarraider** [comment]
Working solution for typesciprt:
```ts
const client: RedisClient;
client = createClient(redisUrl);
```

**Comment by mohemos** [comment]
> 

How did you do this? Please show us the new way, I've tried everything and non worked

**Comment by mohemos** [comment]
I connected mine like this:
`import { createClient } from "redis";

const redis = createClient({
  url: `redis://${process.env.REDIS_HOST}:${process.env.REDIS_PORT}`,
});`

**Comment by kingmanas** [comment]
Still broken, have been stuck on this for 8 hours now. I thought that docker's bridge is assigning wrong aliases, but the issue was here 😞

**Comment by barisvelioglu** [comment]
Still not working

**Comment by vinczebalazs** [comment]
`createClient()` takes in an `options` parameter.

```
import { createClient } from 'redis'

const client = createClient({ url: process.env.REDIS_URL })
```

**Comment by rrozek** [comment]
> `createClient()` takes in an options object as a parameter, you should set the URL there. For more info look at the type definition found under `client.d.ts.` -> `RedisClientOptions`
> 
> ```
> import { createClient } from 'redis'
> 
> const client = createClient({ url: process.env.REDIS_URL })
> ```

createClient({url: REDIS_URL}) worked for me. was struggling for 2h with this. thank you! <3

**Comment by AbdelrahmanAbounida** [comment]
This works for me :
```
import { createClient } from "redis";
const { Url } = require("url");


const url = `redis://${REDIS_DATABASE_HOST}:${REDIS_DATABASE_PORT}`;
const redisClient = createClient({
  url: Url(url),
  password: REDIS_PASSWORD,
});
```
