### ISSUE TITLE
ReplyError: ERR value is not an integer or out of range

### ISSUE THREAD

**Issue by gaurav150493** [NodeRedis/node-redis#1505]
```
ReplyError: ERR value is not an integer or out of range
    at parseError (/opt/bitnami/apache2/htdocs/mylo_node/node_modules/redis-parser/lib/parser.js:193:12)
   at parseType (/opt/bitnami/apache2/htdocs/mylo_node/node_modules/redis-parser/lib/parser.js:303:14)
```

Getting this error randomly.

**Comment by BridgeAR** [comment]
The ReplyError is an indicator that your input is not always correct. You could activate the debug mode to see what is actually passed through. There should also be a bit more information on the error about the data passed through.

**Comment by gaurav150493** [comment]
Actually, in my application I have used `redis.get ` or `redis.set` more than 10000 times. And the API I am calling in which I am getting this error container more than 100 `redis.get` and `redis.set` function so it's hard to find out from exactly which function I am getting this error. Is it any another common way of getting what the actual error is?

**Comment by elimisteve** [comment]
I got this issue because I deleted one int by another (x/y) and ended up with a float; `Math.floor(x/y)` solved it for me.

**Comment by NikitaSmithTheOne** [comment]
> I got this issue because I deleted one int by another (x/y) and ended up with a float; `Math.floor(x/y)` solved it for me.

I agree, ttl has to be integer.
