### ISSUE TITLE
Password option not working

### ISSUE THREAD

**Issue by suityou01** [NodeRedis/node-redis#1509]
### Issue

I have installed node on my host, and am running redis in a docker container. 
The docker container is running and I can connect to it from my host using the command line :-

redis-cli -a mypassword

In node I have the following code

```
const redis = require('redis');
client = redis.createClient({
    password: 'mypassword'
});
```

> Describe your issue here

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

ReplyError: ERR invalid password
```
### Environment

 - **Node.js Version**: 13.11.0
 

 - **Redis Version**: 5.0.8
 

- **Platform**: Ubuntu 18.04

**Comment by stockholmux** [comment]
The `ERR invalid password` is coming straight from Redis - whatever is being passed is not correct. A common problem is connecting to the wrong instance of Redis (e.g. you have a local install of Redis and Docker install and pass the wrong password to the wrong database).

**Comment by thebpmgroup** [comment]
It's not that. There is only one instance of redis running. I can connect from the command line to the docker instance using the password. I have copy pasted the password from the command line to the code. Super meticulous and it still doesn't work.

**Comment by stockholmux** [comment]
The only way you'll get that error is if Redis itself rejected the password. Double check that the password doesn't have non-printable or binary characters that aren't getting mangled by the copy/paste process.

**Comment by thebpmgroup** [comment]
The password is very basic as this is a Dev box. It is similar to the one in the example. There are no non printable characters. I copy paste the password from the redis config to the command line, I can connect. I copy paste to the node server code, I get this error.
