### ISSUE TITLE
Is the RANDOMKEY supported?

### ISSUE THREAD

**Issue by SHwan93** [NodeRedis/node-redis#1513]
### Issue

> Is the RANDOMKEY supported?

---

### Environment

 - **Node.js Version**: `12.14`
 

 - **Redis Version**: `VERSION_HERE`
 

 - **Platform**: `Mac OSX`

**Comment by stockholmux** [comment]
Yep. All commands are covered up to version 5 - so `client.randomkey(...)` should get the job done.
