### ISSUE TITLE
Add support for SET with KEEPTTL

### ISSUE THREAD

**Issue by martinzuern** [NodeRedis/node-redis#1517]
### Issue

Redis 6 introduced support for the `KEEPTTL` flag when using `SET`.
https://redis.io/commands/set

**Comment by stockholmux** [comment]
@martinzuern Works without changes - `KEEPTTL` would just be an argument after your value.

**Comment by gionapaolini** [comment]
> 
> 
> @martinzuern Works without changes - `KEEPTTL` would just be an argument after your value.

How do you provide the options to the set command? I could not find this information in the documentation

**Comment by leibale** [comment]
@gionapaolini 
```javascript
client.set('key', 'value', 'KEEPTTL', (err, reply) => {
  // ...
});
```

**Comment by gionapaolini** [comment]
> 
> 
> @gionapaolini
> 
> ```js
> client.set('key', 'value', 'KEEPTTL', (err, reply) => {
>   // ...
> });
> ```
Thank you @leibale , how do you apply multiple option instead?
I was trying to do SET key value EX 10 NX GET 
(se value with expiry only if not existent, and if exist return it)

**Comment by leibale** [comment]
@gionapaolini
```javascript
client.set('key', 'value', 'EX', '10', 'NX', 'GET', (err, reply) => {
  // ...
});
```

**Comment by gionapaolini** [comment]
> 
> 
> @gionapaolini
> 
> ```js
> client.set('key', 'value', 'EX', '10', 'NX', 'GET', (err, reply) => {
>   // ...
> });
> ```
I already tried that, I still get 
```
ReplyError: ERR syntax error
    at parseError (/app/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14)
```
I'm using redis 3.0.2 btw. Is that supported on this version?

**Comment by leibale** [comment]
@gionapaolini https://github.com/redis/redis-doc/pull/1565

**Comment by LazyCompiler** [comment]
> @gionapaolini
> 
> ```js
> client.set('key', 'value', 'KEEPTTL', (err, reply) => {
>   // ...
> });
> ```

Works like a charm 👌

**Comment by iimanii** [comment]
Why is this closed ? you still can't do something like this

`SET key value KEEPTTL XX`

**Comment by isidoro98** [comment]
Hey @iimanii Have you found a work around to pass both options `KEEPTTL` and `XX` with node-redis?

**Comment by leibale** [comment]
@iimanii @isidoro98
```javascript
client.set('key', 'value', 'KEEPTTL', 'XX', (err, reply) => {
  // ...
});
```

**Comment by isidoro98** [comment]
Thanks that's awesome @leibale.

Are you aware of this type missing in the @types/redis package?

**Comment by leibale** [comment]
@isidoro98 `@types/redis` is not part of `node-redis` and is not maintained by us. We're currently working on v4, which will have TS declarations built-in. Until then, feel free to open a PR in `@types/redis`.

**Comment by isidoro98** [comment]
Awesome, thanks for letting me know! Wasn't aware of that :)

**Comment by vanduc1102** [comment]
my code with `ioredis` typedscript
```

export async function updateObject<T>(key: string, item: T) {
  return redis.set(key, JSON.stringify(item), 'KEEPTTL', 'XX');
}

export async function setObject<T>(key: string, item: T) {
  return redis.set(key, JSON.stringify(item), 'EX', 3600);
}
```

**Comment by wulfsolter** [comment]
For the next person who ends up here. I'm on `redis@4.2.0` and this is what I needed to use

```
await redis.set(key, JSON.stringify(val), { KEEPTTL: true });
```

as per https://github.com/redis/node-redis/blame/a0de7967f98068790cd09c909bbbb7e7d6deefe8/packages/client/lib/commands/SET.ts#L38-L48
