### ISSUE TITLE
node_redis: Deprecated: The ZADD command contains a "undefined" argument.

### ISSUE THREAD

**Issue by Bardankhadka** [NodeRedis/node-redis#1518]
I'm running redis on windows.
And it shows this error when using with node.

node_redis: Deprecated: The ZADD command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.

**Comment by stockholmux** [comment]
I'm going to close this since it is 99.999% an issue with the code using the library.  

Feel free to re-open (with your code) if you can verify that you're not passing an `undefined`.
