### ISSUE TITLE
Cluster support

### ISSUE THREAD

**Issue by howshit** [NodeRedis/node-redis#1521]
Hi there,

Thanks for providing the brilliant redis client.

I've been shifting my redis into a cluster, and I don't find the word "cluster" in the repository except the "Issues" tab.

May I know whether the client supports cluster or not?

Looking forward to your reply.

Best regards,
Felix

**Comment by stockholmux** [comment]
@howshit Check out [redis-clustr](https://www.npmjs.com/package/redis-clustr). It's a wrapper around this library that provides cluster support.

"Native" support for clustering is something that many have considered but I don't think we have a firm timeline on supporting it.
