### ISSUE TITLE
perform properly on Windows，but bug occures in Linux with docker

### ISSUE THREAD

**Issue by mytingbao** [NodeRedis/node-redis#1528]
### Issue

<!--
everything goes well on Window,
but in Linux ,no error,no resonse.
both in windows and linux. logs shows "connect redis success"
when execuate  client.hget  "userList" nothing happened in Linux.

my Dockerfile
FROM node:12.6.0-alpine
MAINTAINER zjc
WORKDIR /code
COPY . /code
ENV NODE_ENV pro
ENV NODE_PORT 3200
ENV REDIS_SERVER *.*.*.*
ENV REDIS_PORT 6379 
ENV REDIS_PASSWORD 123456
RUN npm install
CMD node server.js

my code blow:
// server.js
const redis = require("redis");
const client = redis.createClient(config.redis.port, config.redis.server);
client.auth(config.redis.password);

client.on("connect", () => {
  console.log(config, process.env.NODE_ENV, "redis config");
  console.log("connect redis success");
});

  client.hget("userList", data.username, (err, user) => {
            if (!err && user) {
              const userInfo = JSON.parse(user);
               // doing sth
            } else {
              console.error("该用户不存在，请去注册");
            }
          });

---

### Environment

 - **Node.js Version**: `12.6.0`                -local
 - **Node.js Version**: `12.6.0-alpine`    -docker
 - **Redis Version**: `2.8`

**Comment by stockholmux** [comment]
@mytingbao I'm going to close this issue as we can't possibly help or find a problem out of this issue. 

If you can provide details and a reproducible bug, please re-open and we'll be glad to help if we can.
