### ISSUE TITLE
Cannot read property 'charCodeAt' of undefined

### ISSUE THREAD

**Issue by lloonnyyaa** [NodeRedis/node-redis#1529]
### Issue

when importing a package `const redis = require("redis");` in the console, an error appears: `TypeError: Cannot read property 'charCodeAt' of undefined`
---

### Environment
 - **Node.js Version**: `14.5.0`
 - **Redis Version**: `6.0.5`

Has anyone encountered such a problem? there is a solution?

**Comment by DevDecrux** [comment]
I've encountered the same problem. Can somebody help me?
I am using VueJS and trying to import package by const redis = require("redis");

**Comment by lloonnyyaa** [comment]
> I've encountered the same problem. Can somebody help me?
> I am using VueJS and trying to import package by const redis = require("redis");
> 
> Edit: Oh, it cannot be used in the browser... i get it now.

this package only works on the server.
it will not work on the client, so it cannot be built through cli
