### ISSUE TITLE
Any chance to add LPOS command?

### ISSUE THREAD

**Issue by yepMad** [NodeRedis/node-redis#1535]
LPOS was added to Redis in version 6.0.6. Any chance of being added to this library?

https://redis.io/commands/lpos

**Comment by oliverjessner** [comment]
friendly bump

**Comment by imranaalam** [comment]
> Install or update node-redis and you can use LPOS

can't do so. lpos cant be searched in node-redis repo.

**Comment by IsAmrish** [comment]
> Install or update node-redis and you can use LPOS

LPOS not present at least in v3.0.2. Typescript intellisense is not giving any suggestion about `lpos` or `LPOS`.
