### ISSUE TITLE
ERR wrong number of arguments for 'set' command

### ISSUE THREAD

**Issue by theromie** [NodeRedis/node-redis#1536]
### Environment

 - **Node.js Version**: `v12.18.0`
 

 - **Redis Version**: `2.4.6`
 

 - **Platform**: `Windows 10`

I am using Redis on a Windows machine and using it in Node JS and want to set expire time using `CLIENT.SET` but it gives me an error.
`
let id=2;
let token="asndakj";
let REDIS_EXPIRE = 30;
let redisEx = REDIS_EXPIRE * 60 * 60 * 24;
client.SET(id, token, 'EX', redisEx, (err, reply) => {})
`

**Comment by Loksly** [comment]
Hi!

Have you tried `SETEX` command?

```
(method) Commands<boolean>.setex(key: string, seconds: number, value: string, cb?: Callback<string> | undefined): boolean
```

```javascript
const redisclient = createClient();
// set key for 1 minute (60 seconds)
redisclient.setex("key", 60, "value", (err, reply) => {
    if (err) {
        console.error(err);
    } else {
        console.debug(reply);
    }
});
```

**Comment by theromie** [comment]
Thanks, It's working
