### ISSUE TITLE
Support for smismember

### ISSUE THREAD

**Issue by Wyctus** [NodeRedis/node-redis#1557]
Seems like `node-redis` doesn't support the `smismember` command, which is like `sismember` but works for multiple values in one call. Is there any chance that this will be supported in the near future?

**Comment by ncjones** [comment]
The "SMISMEMBER" command, among others, have been added in the recent Redis 6.2 preview releases. See "new commands" in the release notes for [6.2-rc1][] and [6.2-rc2][]. I guess these need to be added in commands.json in the [redis-commands][] package. Personally, I am looking for the "XAUTOCLAIM" command.

[6.2-rc1]: https://github.com/redis/redis/releases/tag/6.2-rc1
[6.2-rc2]: https://github.com/redis/redis/releases/tag/6.2-rc2
[redis-commands]: https://github.com/NodeRedis/redis-commands

**Comment by stockholmux** [comment]
Yep, that request would go to `redis-commands`.
