### ISSUE TITLE
DigitalOcean Redis Connection Error

### ISSUE THREAD

**Issue by GabrielBlink32** [NodeRedis/node-redis#1558]
### Issue

> I'm using DigitalOcean Redis provider to host my redis server but i can't connect with the server in nodejs
Error:
`Error  AbortError: Ready check failed: Redis connection lost and command aborted. It might have been processed.
    at RedisClient.flush_and_error (C:\Users\Gabriel\Desktop\atlas-api-master\node_modules\redis\index.js:297:23)
    at RedisClient.connection_gone (C:\Users\Gabriel\Desktop\atlas-api-master\node_modules\redis\index.js:602:14)
    at Socket.<anonymous> (C:\Users\Gabriel\Desktop\atlas-api-master\node_modules\redis\index.js:230:14)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'UNCERTAIN_STATE',
  command: 'INFO'`

My code:
`import redis, { RedisClient } from "redis";

class RedisInstance {
  public client: RedisClient;

  public connect(): void {
    try {
      this.client = redis.createClient({
        host: "$",
        port: 1,
        password: "$",
      });
      this.client.on("error", function(err) {
        console.log("Error ", err);
      });
      console.log("[Atlas API - Redis] Redis ready");
    } catch (ex) {
      console.log("[Atlas API - ERROR] Redis error.");
    }
  }
}

export default new RedisInstance();
`

---

### Environment

 - **Node.js Version**: `v12.18.2`
 

 - **Redis Version**: `^3.0.2`
 

 - **Platform**: `Windows 10`

**Comment by goktugyil** [comment]
how did you solve this?

**Comment by GabrielAtlas** [comment]
> how did you solve this?

Use the redis URI to connect

**Comment by goktugyil** [comment]
I was using typeorm and needed to add this as well:

```
        cache: {
            type: 'redis',
            options: {
                username: process.env.REDIS_USERNAME,
                host: process.env.REDIS_HOST,
                port: process.env.REDIS_PORT,
                password: process.env.REDIS_PASSWORD,
                tls: process.env.REDIS_TLS == 'true' ? true : false,
            },
            duration: 1000 * 3, // 3 seconds
        },
```
