### ISSUE TITLE
What is this module status? Is it alive?

### ISSUE THREAD

**Issue by gkorland** [NodeRedis/node-redis#1566]
It seems like the last PR was merged about a year ago and many issues/PRs are pending, is this repository maintained? 

Is there a way I/we can help/contribute to make this module alive? 

@Salakar

**Comment by sean256** [comment]
I came here looking for the same answer. The readme suggests that v4 is under active development, but the v4 branch hasn't had activity in 3 years.

**Comment by DoWhileGeek** [comment]
How can like, _the_ redis client for node be abandonware?

**Comment by sean256** [comment]
I haven't a clue, but because of the lack of activity here I discovered https://github.com/luin/ioredis
It has the long promised promises!

**Comment by itamarhaber** [comment]
Hello @Salakar,

I'm mentioning you directly here as it appears that you are the sole maintainer for this package. If I'm mistaken and there additional maintainers please forgive my omission and consider yourselves addressed as well.

This project has long been the de-facto standard for the domain and is being relied upon by many members of the Redis community. Given its maturity and popularity vis a vis the lack of attention that the project has been getting, we'd (Redis Labs) like to offer our help and work together in any way that's agreeable with you and the project's community in maintaining and/or developing it. Our interests (and I'm taking the liberty of speaking on behalf of both the OSS and the commercial Redis ecosystems) are to maximize the project's benefits whilst ensuring its sustainability - we're looking forward to a fruitful collaboration and your thoughts on the matter.

Cheers,
Itamar
