### ISSUE TITLE
GHSL-2021-026

### ISSUE THREAD

**Issue by kevinbackhouse** [NodeRedis/node-redis#1569]
Hi,

GitHub Security Lab has found a potential vulnerability in node-redis. Please could you let us know how to contact you privately? We recommend adding a [SECURITY.md](https://docs.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) to your repository with a contact email address, which you can do by going to the [Security tab](https://github.com/NodeRedis/node-redis/security) and clicking the "Set up a security policy" button.

Kind regards,

Kevin Backhouse
GitHub Security Lab

**Comment by gkorland** [comment]
@kevinbackhouse thanks for letting us know, please send me a direct email

**Comment by kevinbackhouse** [comment]
Thanks! I have sent you an email.
