### ISSUE TITLE
Are ZDIFF and ZDIFFSTORE supported?

### ISSUE THREAD

**Issue by clarkewd** [NodeRedis/node-redis#1575]
### Issue

When I try and use `zdiff` I get the error `client.zdiff is not a function`

From the [redis documentation page](https://redis.io/commands/zdiff) it mentions this command is `Available since 6.2.0` and I'm using `6.2.1`

---

### Environment

 - **Node.js Version**: 14
 

 - **Redis Version**: 6.2.1
 

 - **Platform**: node:14 (docker image)

And from `package.lock`:

      "redis": {
        "version": "3.0.2",
        "resolved": "https://registry.npmjs.org/redis/-/redis-3.0.2.tgz",
        "integrity": "sha512-PNhLCrjU6vKVuMOyFu7oSP296mwBkcE6lrAjruBYG5LgdSqtRBoVQIylrMyVZD/lkF24RSNNatzvYag6HRBHjQ==",
        "requires": {
          "denque": "^1.4.1",
          "redis-commands": "^1.5.0",
          "redis-errors": "^1.2.0",
          "redis-parser": "^3.0.0"
        }
      },
      "redis-commands": {
        "version": "1.6.0",
        "resolved": "https://registry.npmjs.org/redis-commands/-/redis-commands-1.6.0.tgz",
        "integrity": "sha512-2jnZ0IkjZxvguITjFTrGiLyzQZcTvaw8DAaCXxZq/dsHXz7KfMQ3OUJy7Tz9vnRtZRVz6VRCPDvruvU8Ts44wQ=="
      },
      "redis-errors": {
        "version": "1.2.0",
        "resolved": "https://registry.npmjs.org/redis-errors/-/redis-errors-1.2.0.tgz",
        "integrity": "sha1-62LSrbFeTq9GEMBK/hUpOEJQq60="
      },
      "redis-parser": {
        "version": "3.0.0",
        "resolved": "https://registry.npmjs.org/redis-parser/-/redis-parser-3.0.0.tgz",
        "integrity": "sha1-tm2CjNyv5rS4pCin3vTGvKwxyLQ=",
        "requires": {
          "redis-errors": "^1.0.0"
        }
      },

**Comment by leibale** [comment]
We're working now on adding the missing features from Redis 6 to the module, but It'll take some time.
In the mean time you can use `client.sendCommand` as an workaround:
```
client.sendCommand('ZDIFF', ['a', 'b', 'c'], (err, result) => {
  // ...
});
```

**Comment by clarkewd** [comment]
Thank you!
