### ISSUE TITLE
Prefix not work?

### ISSUE THREAD

**Issue by DoubleSH** [NodeRedis/node-redis#1584]
I try:
const subscribe = redis.createClient({prefix:'live:'});
subscribe.subscribe("chat");
and
const subscribe = redis.createClient();
subscribe.subscribe("live:chat");

Not working.

In console redis-cli "subscrive live:chat" work.

### Issue

> Describe your issue here

---

### Environment

 - **Node.js Version**: `8.17`
 

 - **Redis Version**: `3.2.6`
 

 - **Platform**: `debian`

**Comment by leibale** [comment]
Currently prefixes works only with keys, not channel names.
```javascript
const subscribe = redis.createClient();
subscribe.subscribe("live:chat");
```
should work
