### ISSUE TITLE
Unresolved variable mget

### ISSUE THREAD

**Issue by galliroberto** [NodeRedis/node-redis#1585]
### Issue

> Unresolved variable mget

```
const {promisify} = require('util')

const redis = require("redis");
const client = redis.createClient({host: 'ws_redis'});

const amget = promisify(client.mget).bind(client)
```

---

### Environment

 - **Node.js Version**: `node:14-alpine`
 

 - **Redis Version**: `6.2.1`
 

 - **Platform**: `Win10 - WSL2 - docker - redis-alpine`
 

 - **Library Version**: `3.0.2`

**Comment by leibale** [comment]
Can you please share the error message?

**Comment by galliroberto** [comment]
I retry now and the error gone.
I think that I had mapped async a function does not exist in redis.

Sorry 

When i put cursor on mget, phpstorm tell me that mget is Unresolved variable mget
