### ISSUE TITLE
Request to publish next version of node module

### ISSUE THREAD

**Issue by yashchaudharii25** [NodeRedis/node-redis#1587]
### Issue

We could see that support is added for Redis 6, to make use of the `username` for authentication.

The PR https://github.com/NodeRedis/node-redis/pull/1508 is merged and issue https://github.com/NodeRedis/redis-commands/pull/35 is closed. However, the changes are not published yet.

Could you please publish the changes?

**Comment by yashchaudharii25** [comment]
@Salakar @leibale @gkorland  - We have used this node module in our application and wanted to add support for Redis 6 on priority. 

It would be great help if next version of node module can be published, to deliver the changes mentioned in issue description, along with required changes, if any to support the Redis 6.

Thank you.

**Comment by gkorland** [comment]
We are working on the final steps before we release it

**Comment by leibale** [comment]
@yashchaudharii25 We just released version 3.1.0
