### ISSUE TITLE
Redis EXISTS not available or am I blind?

### ISSUE THREAD

**Issue by Urento** [NodeRedis/node-redis#1596]
### Issue

> Describe your issue here
I was not able to find the EXISTS Method in your documentation. Am I blind or is it not implemented yet or is there an more elegant way to check if a key already exists?

**Comment by leibale** [comment]
@Urento 
I'm not sure if it's mentioned in the docs, but the `exists` command is implemented, and you can use it just like any other command:
```javascript
client.exists(key, (err, isExists) => {
  if (err) {
    return console.error(err);
  }

  console.log(isExists);
});
```

**Comment by Urento** [comment]
@leibale Okay, thank you!
