### ISSUE TITLE
Getting "ERR syntax error" on set using node-redis

### ISSUE THREAD

**Issue by vikramaditya234** [NodeRedis/node-redis#1599]
### Issue

I am unable to set and get key in redis using node-redis. But set and get works well when using redis-cli.
This is my code:
 
    const redis = require('redis');
    const util = require('util');

    const GLOBAL_KEY = 'lambda-test';
    const redisOptions = {
        host: process.env.REDIS_HOST,
        port: process.env.REDIS_PORT
    }

    try{
        test();
    }
    catch(err) {
        console.log('catch err ' + err);
    }

    async function test() {
        var client = redis.createClient(redisOptions);
        client.on("error", function(error) {
            console.error(error);
        });
        client.get = util.promisify(client.get);
        client.set = util.promisify(client.set);
        await client.set("ke", "test1", redis.print).catch(function(err){console.log('err: '+ err);});
        await client.get("ke", redis.print).catch(function(err){console.log('err: '+ err);});
    }

Output:

    err: ReplyError: ERR syntax error
    err: ReplyError: ERR wrong number of arguments for 'get' command

Can't figure what the reason is, can anyone help me figure what I am missing?

I also tried using bind, but no luck:

        client.get = util.promisify(client.get).bind(client);
        client.set = util.promisify(client.set).bind(client);

Also I have enabled the DEBUG to get extra logs:

    2021-04-20T07:48:36.279Z Queueing set for next server connection.
    2021-04-20T07:48:36.303Z Stream connected XXXXX:6379 id 0
    2021-04-20T07:48:36.303Z Checking server ready state...
    2021-04-20T07:48:36.304Z Send XXXXXX:6379 id 0: *1
    $4
    info

    2021-04-20T07:48:36.305Z Net read XXXXX:6379 id 0
    2021-04-20T07:48:36.306Z Redis server ready.
    2021-04-20T07:48:36.306Z on_ready called XXXXX:6379 id 0
    2021-04-20T07:48:36.307Z Sending offline command: set
    2021-04-20T07:48:36.307Z Send XXXXX:6379 id 0: *4
    $3
    set
    $2
    ke
    $5
    test1
    $187
    function print (err, reply) {
        if (err) {
            // A error always begins with Error:
            console.log(err.toString());
        } else {
            console.log('Reply: ' + reply);
        }
    }

    2021-04-20T07:48:36.307Z Net read XXXXX:6379 id 0
    err: ReplyError: ERR syntax error
    2021-04-20T07:48:36.309Z Send XXXXX:6379 id 0: *3
    $3
    get
    $2
    ke
    $187
    function print (err, reply) {
        if (err) {
            // A error always begins with Error:
            console.log(err.toString());
        } else {
            console.log('Reply: ' + reply);
        }
    }

    2021-04-20T07:48:36.310Z Net read XXXXX:6379 id 0
    err: ReplyError: ERR wrong number of arguments for 'get' command

---

### Environment

 - **Node.js Version**: `v12.22.1`
 

 - **Redis Version**: `redis-cli 3.2.12`
 

 - **Platform**: `Amazon Linux 2`

**Comment by leibale** [comment]
There are 2 things you need to fix in your code:
1. You have to `.bind` the `client` to the function begin returned from `util.promisify`.
2. `redis.print` intended to be used as a callback, not as a `.then` of a promise.

```javascript
async function test() {
    const client = redis.createClient(redisOptions);
    client.on("error", function(error) {
        console.error(error);
    });
    client.get = util.promisify(client.get).bind(client);
    client.set = util.promisify(client.set).bind(client);

    try {
        console.log('SET reply:', await client.set("ke", "test1"));
    } catch (err) {
        console.error(err);
    }

    try {
        console.log('GET reply:', await client.get("ke"));
    } catch (err) {
        console.error(err);
    }
}
```

**Comment by Elvis1221** [comment]
Hi. Could you tell me please.
How i can unit test it in jest?
![image](https://user-images.githubusercontent.com/68077916/194705740-ccf87e5d-dae6-4d6c-a901-6bb38c1af9a3.png)

**Comment by leibale** [comment]
@Elvis1221 just pass an empty listener to make sure an error won't crash the process

```javascript
// ...

client.on('error', () => {
  // noop
});

// ,,,
```
