### ISSUE TITLE
TypeScript: rpush: "Expected 0 arguments, but got 2."

### ISSUE THREAD

**Issue by Iipal** [NodeRedis/node-redis#1602]
###  TypeScript Issue

When trying to use rpush got this error in Typescript:
![image](https://user-images.githubusercontent.com/31858171/115705386-23ad6780-a375-11eb-92d2-6d71d2ffb841.png)

---

### Environment

 - **Node.js Version**: v14.16.1
 

 - **Redis Version**: redis version run in docker: 
![image](https://user-images.githubusercontent.com/31858171/115705571-5e170480-a375-11eb-9871-953f14fca46c.png)

but installed via npm is `"redis": "^3.1.2"` and `"@types/redis": "^2.8.28"`
 

 - **Platform**: Ubuntu 20.04.2

**Comment by Iipal** [comment]
fixes the problem, before the problem line:
```// @ts-ignore```

But I still leave this issue open because I think it's not how it's must work

**Comment by leibale** [comment]
The types for v3 are maintained by [`DefinitelyTyped`](https://github.com/DefinitelyTyped//blob/master/types/redis), please open the issue there.
