### ISSUE TITLE
Updated changelog after 3.0.0 

### ISSUE THREAD

**Issue by sozakir** [NodeRedis/node-redis#1604]
### Issue

The latest version is 3.1.2 but there is not changelog updated after version 3.0.0. Please update the changelog with the new versions.

https://github.com/NodeRedis/node-redis/blob/master/CHANGELOG.md

> Describe your issue here

---

### Environment

 - **Node.js Version**: `VERSION_HERE`
 

 - **Redis Version**: `VERSION_HERE`
 

 - **Platform**: `PLATFORM_HERE`

**Comment by leibale** [comment]
You can see the changes in the [releases tab](https://github.com/NodeRedis/node-redis/releases)
