### ISSUE TITLE
What's the correct way to shutdown the Redis Server through `node-redis`?

### ISSUE THREAD

**Issue by raphael10-collab** [NodeRedis/node-redis#1606]
What's the correct way to shutdown the Redis Server through `node-redis`?

The following :

    import redis from "redis";
    const redis_client = redis.createClient();

    redis_client.sendCommand("SHUTDOWN", function() {
      console.log("Shutting down Redis Server ...");
    });

doesn't produce the desired effect

OS: Ubuntu 18.04
redis: v 6.2.3
node-redis:  v. 3.1.0

**Comment by Dhyeythumar** [comment]
The following line is mentioned in the readme
> This library is a 1 to 1 mapping of the [**Redis commands**](https://redis.io/commands).

So I think it should be:
```
import redis from "redis";
const redis_client = redis.createClient();

redis_client.shutdown(function(err, res) {
  console.log("Shutting down Redis Server ...");
});
```

For more information you can refer this [**redis.io/commands/shutdown**](https://redis.io/commands/shutdown).

**Comment by raphael10-collab** [comment]
@Thanks @Dhyeythumar !!
Before I solved using this "trick":

    const childProcess = require('child_process');
    const redisServerShutdown = () => {
      childProcess.exec("src/scripts/redis/redis-cli shutdown", (error) => {
        if (error) {
          console.log(error);
        }
      });
    };
