### ISSUE TITLE
redis.hkeys is not a function

### ISSUE THREAD

**Issue by dhyeythumar** [NodeRedis/node-redis#1609]
### Issue

I want all the field names in the hash stored at key. And I am using Redis Enterprise Cloud (the free version) but while executing `redis.hkeys` I am getting the following error `TypeError: redis.hkeys is not a function`.
So I want to know is this command available or not in node-redis?

Following code:
```
redis.hkeys(key, (err, res) => {
    if (err) console.log(err);
    else console.log(res);
});
```

---

### Environment

 - **Node.js Version**: 14.15.3

 - **node-redis Version**: 3.1.2
 

 - **Redis Version**: 6.0.9
 

 - **Platform**: Windows 10

**Comment by kpbird** [comment]
**It's working for me.**

1. Node-Redis Version: 3.1.2
2. Redis Version: Redis 6.2.4
3. Platform: OS X (11.2.3)

```
const redis = require("redis");
const client = redis.createClient();

client.hset("test","name","ketan","country","India")
 client.hkeys("test",function(err, value) {
    console.log(value);
  });

```

Output
```
testNodeRedis node index.js
[ 'name', 'country' ]
```

**Comment by dhyeythumar** [comment]
Hi @kpbird,
I didn't test this command again after getting the issue until you said that it's working so now I again tested this command and it started working (I am using Redis Lab). So I am closing this issue. And thanks for replying ✌.
