### ISSUE TITLE
LMOVE and BLMOVE commands not supported

### ISSUE THREAD

**Issue by Aex12** [NodeRedis/node-redis#1610]
Is there any plans to implement this commands?

https://redis.io/commands/lmove
https://redis.io/commands/blmove

Or is there any simple way to extend a redis instance to support new commands that are not yet implemented?

**Comment by leibale** [comment]
those commands were added in v3.1.0, and you can use the like any other commands:
```javascript
cliemt.lmove('source', 'destination', 'LEFT', 'RIGHT', (err, reply) => console.log(err, reply));
client.blmove('source', 'destination', 'LEFT', 'RIGHT', (err, reply) => console.log(err, reply));
```
also, you can always use `sendCommand` directly:
```javascript
client.sendCommand('command', ['arg1', 'arg2'], (err, reply) => console.log(err. reply));
```

**Comment by Aex12** [comment]
Guess the problem is on the typings package then, which is missing declarations for those two commands. 
I did a quick search on this repo and found no code references for lmove and blmove and thought they weren't supported. Now, after digging a bit more I found they are defined on a JSON file in another repo.
