### ISSUE TITLE
Why does node-redis not use API key?

### ISSUE THREAD

**Issue by curiolearner** [NodeRedis/node-redis#1613]
### Question

Forgive my ignorance and specifically for the Redis Cloud and not own-hosting, I wonder why does the node-redis not include the use of  API key?  Does it make the usage any better ?

**Comment by leibale** [comment]
@curiolearner Can you please explain what API key are you talking about?

**Comment by curiolearner** [comment]
In the Redislabs' Enterprise Cloud, under settings "Cloud API Access Key".

**Comment by leibale** [comment]
I can't find "Cloud API Access Key", but if you are talking about "Access Control & Security" this is the default user password, and it should be provided when creating a client (look at the `url` or `password` options for [redis.createClient](https://github.com/NodeRedis/node-redis#rediscreateclient))
![image](https://user-images.githubusercontent.com/7086055/120508831-0ae19a00-c396-11eb-8711-067ac36bc5bb.png)
