### ISSUE TITLE
Multiple radis server

### ISSUE THREAD

**Issue by rupamking1** [NodeRedis/node-redis#1619]
how to add Multiple radis server.

**Comment by NovaAtWarren** [comment]
To connect to multiple Redis instances, you'll need to create multiple connections.

Please note, for the following example, `192.168.0.2` and `192.168.0.3` are the redis hosts.
```js
const redisConnection1 = redis.createConnection(6379, "192.168.0.2");
const redisConnection2 = redis.createConnection(6379, "192.168.0.3");
```
