### ISSUE TITLE
redis log does not contain year

### ISSUE THREAD

**Issue by chithrasarathy** [NodeRedis/node-redis#1620]
Redis log from installer folder does not have year. i am having same month data of same year.

**Comment by chithrasarathy** [comment]
![image](https://user-images.githubusercontent.com/48916834/123433059-adcdb280-d5e8-11eb-84bb-26153ce6c03d.png)

**Comment by NovaAtWarren** [comment]
An issue with your Redis server, even if it's only logging, will have to be brought up over at [the Redis repository](https://github.com/redis/redis), as node-redis is only an API for use with Javascript.
