### ISSUE TITLE
6.2 commands (getex etc)

### ISSUE THREAD

**Issue by arcanis** [NodeRedis/node-redis#1621]
### Issue

Redis 6.2 seems to [introduce](https://redislabs.com/blog/redis-6-2-the-community-edition-is-now-available/) a bunch of new commands such as [`getex`](https://redis.io/commands/getex), but they don't seem to be exposed by node-redis just yet.

**Comment by leibale** [comment]
v3 uses [this json](https://github.com/NodeRedis/redis-commands/blob/master/commands.json) to extend the client, every command you find there, is supported by the client.

This should work:"
```javascript
client.getex('key', 'EX', '10', (err, reply) => {
  // ...
});
```

**Comment by arcanis** [comment]
Ah, thanks! I got mistaken by the `@types/redis` package, and the lack of matches when doing a grep search in the repo. Thanks for the pointer!
