### ISSUE TITLE
NOAUTH Authentication required

### ISSUE THREAD

**Issue by sell** [NodeRedis/node-redis#1631]
### Issue
When testing locally I get no errors and authentication is fine, then when I push the code to the server where the redis DB is hosted i get `NOAUTH Authentication required`, I tried many different ways to connect and the errors still occurs. Here is my code:
```js
const REDIS_PORT = process.env.REDIS_PORT || 6379;
const { REDIS_HOST, REDIS_PWD } = process.env;

const client = redis.createClient(REDIS_PORT, REDIS_HOST);
client.auth(REDIS_PWD, (err) => {
  if (err) {
    throw err;
  }
});
```

I binded `0.0.0.0` in my redis.conf so I can test locally and it worked but when trying on server where db is hosted I get the authentication issue.

---

### Environment

 - **Node.js Version**: `12.22.2`
 

 - **Redis Version**: `^3.1.2`
 - **Local Machine: Redis Server Version**: `6.2.4`
 - **Servers Machine: Redis Server Version**: `4.0.9`
 

 - **Local Machine Platform**: `macOS Big Sur`
 - **Servers Platform**: `Ubutntu 18.04`

**Comment by leibale** [comment]
Set the password on the connection rather then executing the auth command one time:
```javascript
const client = redis.createClient({
  host: REDIS_HOST,
  port: REDIS_PORT,
  password: REDIS_PWD
});
```

**Comment by sell** [comment]
Hello @leibale,

Forgot to close this, I just went with using the uri string.

```js
const client = redis.createClient(REDIS_URL);
```
This is was the only way it worked both locally and on my server.

Anyway, thanks for the help of maintaining of node redis.
