### ISSUE TITLE
v4 configuration questions

### ISSUE THREAD

**Issue by jpike88** [NodeRedis/node-redis#1641]
I'm testing the v4 RC, and have a couple of questions about migrating configuration which isn't currently answered in the new documentation:

```enable_offline_queue``` seems to be removed. I wanted this to always be false because I didn't want a risk of things backing up on my API instance.

Also, ```connect_timeout``` is removed and seemed to be replaced by the items in ```isolationPoolOptions```, but there are 3 different timeout related properties there. Which one is equivalent?

And last, ```retry_strategy``` has been replaced by ```reconnectStrategy``` (I think), but looks like the old property ```total_retry_time``` is gone, there's just a single number representing retry/attempt count, correct? 

Thanks for the hard work!

**Comment by leibale** [comment]
The "offline queue" was removed (and accidentally wasn't added to the changelog).
You can read more about the current/new behavior in the [updated changelog](https://github.com/NodeRedis/node-redis/blob/v4/CHANGELOG.md), or in the [FAQ](https://github.com/NodeRedis/node-redis/blob/v4/docs/FAQ.md).

The `connect_timeout` was mistakenly removed - it's back now (as `connectTimeout`).
BTW, `isolationPoolOptions` is a totally different feature, you can read more about it in the [Isolated Execution Guide](https://github.com/NodeRedis/node-redis/blob/v4/docs/isolated-execution.md).

Regarding `retry_strategy` - yup, you are 100% correct.

Thanks for trying the RC version! :)

**Comment by jpike88** [comment]
thanks, when is another RC going to be out?

**Comment by leibale** [comment]
@jpike88 we got a couple more issues, I'll fix them all, and then release another RC. It'll take about 1-2 days.
