### ISSUE TITLE
(v4.0.0-rc.0) xReadGroup throws TypeError on timeout and read

### ISSUE THREAD

**Issue by anthonyting** [NodeRedis/node-redis#1642]
### Issue

When xReadGroup times out with the `BLOCK` option, it should return null, but it throws an error
```
TypeError: Cannot read property 'map' of null
    at Object.transformReplyStreamsMessages [as transformReply] (\...\redis\dist\lib\commands\generic-transcommands\generic-transformers.js:121:18)
    at RedisClient.commandsExecutor (\...\redis\dist\lib\client.js:104:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    ...
```

From `generic-transformers.js`, reply is null here:
```javascript
function transformReplyStreamsMessages(reply) {
    return reply.map(([name, rawMessages]) => ({
        name,
        messages: transformReplyStreamMessages(rawMessages)
    }));
}
```

Example code:
```javascript
await redis.xGroupCreate('STREAM_KEY', 'GROUP_NAME', '$', {
    MKSTREAM: true
});

await redis.xReadGroup('GROUP_NAME', 'CONSUMER_ID', {
    id: '>',
    key: 'STREAM_KEY'
}, {
    BLOCK: 500
});
```

---

Also, when it doesn't time out, it throws a different TypeError.
```
TypeError: Cannot read property 'length' of undefined
    at transformReplyTuples (\...\redis\dist\lib\commands\generic-transformers.js:103:31)
    at transformReplyStreamMessages (\...\redis\dist\lib\commands\generic-transformers.js:115:22)
    at \...\redis\dist\lib\commands\generic-transformers.js:124:19
    at Array.map (<anonymous>)
    at Object.transformReplyStreamsMessages [as transformReply] (\...\redis\dist\lib\commands\generic-transformers.js:122:18)
    at RedisClient.commandsExecutor (\...\redis\dist\lib\client.js:104:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    ...
```

Example code:
```javascript
await redis.xGroupCreate('STREAM_KEY', 'GROUP_NAME', '$', {
    MKSTREAM: true
});

await redis.xAdd('STREAM_KEY', '*', {
    'a': 'b',
    'c': 'd'
});

await redis.xReadGroup('GROUP_NAME', 'CONSUMER_ID', {
    id: '>',
    key: 'STREAM_KEY'
});
```

The error comes from `generic-transformers.js`, where it passes undefined to `transformReplyTuples`. Iterating over reply[0] instead of reply works in this case, since the object ends up being `[['1630348161935-0',[ 'a', 'b', 'c', 'd' ]]]`

```javascript
function transformReplyStreamMessages(reply) {
    const messages = [];
    for (let i = 0; i < reply.length; i += 2) {
        messages.push({
            id: reply[i],
            message: transformReplyTuples(reply[i + 1])
        });
    }
    return messages;
}
```

---

### Environment

 - **Node.js Version**: `v14.17.5`
 

 - **Redis Version**: `6.2.5`
 

 - **Platform**: `Windows 10`
 
 - **Node-Redis Version**: `v4.0.0-rc.0`

**Comment by leibale** [comment]
Hi @anthonyting, I've fixed this (and a couple of more issues with stream commands) in 815c9c8.
It'll be released in the next RC version (in the next few days).

**Comment by battika** [comment]
Thans @leibale for fixing it. I have the same exact issue and it would be good to have the fix available. Do you know when the next RC will be released? Thanks!

**Comment by leibale** [comment]
@battika this week.
In the meantime you can:
Clone the repo
Checkout to the v4 branch
Run `npm install`
Run `npm build`
Use the local version (either by coping the dist folder into the node_modules in your project, or by using npm link)

**Comment by leibale** [comment]
@anthonyting @battika `4.0.0-rc.1` is on npm! :)
