### ISSUE TITLE
Command EXISTS always returning true

### ISSUE THREAD

**Issue by elfpileggi** [NodeRedis/node-redis#1646]
### Issue
I'm using the EXPIRE command to auto remove the key and after the key expired when I use the EXISTS command from the js library the result is always true, but when I run the command in the terminal via redis-cli, it's returning 0
---

### Environment

 - **Node.js Version**: `16.4.2`
 

 - **Redis Version**: `6.0.15`
 

 - **Platform**: `Ubuntu 20.04`

**Comment by leibale** [comment]
@elfpileggi which version of node-redis are you using? can you please share your code?

**Comment by elfpileggi** [comment]
It's the last version, 3.1.2

```
const { createClient } = require('redis');

(async () => {
    const client = createClient();

    client.on('error', (err) => console.log('Redis Client Error', err));

    await client.set('key_test', 'value');
    await client.expire('key_test', 5);

    setInterval(async () => {
      const exists = await client.exists('key_test');
      console.log('exists "key" - ', exists);
    }, 1000);
})();
```

this is the result for me:

```
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
exists "key" -  true
```

**Comment by leibale** [comment]
It looks like the code you are using was copied from the v4 README, try to install `redis@next` (note: it's still pre-release).

Or, if you wanna use v3, [you need to "promisify" the client](https://github.com/NodeRedis/node-redis/tree/v3.1#promises).

**Comment by elfpileggi** [comment]
Using `promisify` is working, but I tried using `redis@next` and got weird behavior, the app stopped responding when I try to use a command with await or then().catch()

I guess we can close this then.
Thanks!
