### ISSUE TITLE
Client doesn't have Redis commands

### ISSUE THREAD

**Issue by Khuzha** [NodeRedis/node-redis#1649]
I'm creating a client like this:

```
const client = createClient({
  socket: {
    host: process.env.REDIS_HOST,
    port: +process.env.REDIS_PORT!,
    password: process.env.REDIS_PASSWORD
  }
});
```
`createClient` is imported this way: `import { createClient } from 'redis';`

And when I try to call any Redis command on this client, e.g.:

`client.rpush('key', 'value');`

I get an error: `this.client.rpush is not a function`

And `console.log(Object.keys(client));` output is:

```
[
  '_events',
  '_eventsCount',
  '_maxListeners',
  'select',
  'subscribe',
  'pSubscribe',
  'unsubscribe',
  'pUnsubscribe',
  'quit'
]
```

Am I doing something wrong? And how can I fix it?

**Comment by NovaAtWarren** [comment]
Could you tell us what version of node-redis you have installed please?

**Comment by leibale** [comment]
@Khuzha by the result from `Object.keys(client)` I guess you are trying to use the `next` version.
Try to use `rPush` or `RPUSH` instead of `rpush`. You can read more about the commands name convention [here](https://github.com/NodeRedis/node-redis#redis-commands).
