### ISSUE TITLE
`setEx` method doesn't accept `Buffer` as value type

### ISSUE THREAD

**Issue by maximelafarie** [NodeRedis/node-redis#1650]
### Issue

Normally, redis is able to handle key-buffer storage (and not only key-string storage). As I want to store a buffer, typescript returns an error if I try to provide the to the `setEx` or `set` methods something else than a string.

So my question is: Is there any (documented) way to store and retrieve (neatly) a buffer in redis?

Regards! 🖖 

---

### Environment

 - **Node.js Version**: `@next`

 - **Redis Server Version**: `6.2.4`

 - **Platform**: `Mac OSX 11.2.3`

**Comment by leibale** [comment]
@maximelafarie with the new changes you can now:
1. Use `SET/set` with buffer as the key and/or the value.
2. Use the `GET_BUFFER/getBuffer` command to get a value as a buffer (rather than a string).

I'll release a new RC (with those changes) in a few days.
