### ISSUE TITLE
delete not working on 4.0.0-rc.1

### ISSUE THREAD

**Issue by jpike88** [NodeRedis/node-redis#1653]
### Issue

> Describe your issue here

Tried the release candidate, redisclient.delete just doesn't work.

---

### Environment

 - **Node.js Version**: 12.20.0

 - **Redis Server Version**: 6.0.5

 - **Platform**: Amazon Linux 2

**Comment by leibale** [comment]
The command name is [`DEL`](https://redis.io/commands/del), not `DELETE`. `client.DEL` and `client.del` should work.

**Comment by jpike88** [comment]
This issue should be reopened, because the root issue is that typing is not up to speed. 
<img width="654" alt="Screenshot 2021-09-15 at 6 26 08 PM" src="https://user-images.githubusercontent.com/9585787/133424975-07bc324e-c6c2-4042-b665-7b12ac9d3cc1.png">

```RedisClientType<RedisModules, RedisLuaScripts>``` doesn't expose explicit method definitions, it's too easy to make a mistake and not notice until using a real redis server.
