### ISSUE TITLE
Prefix option

### ISSUE THREAD

**Issue by joacub** [NodeRedis/node-redis#1657]
prefix option is not longer available, what is the suggestion for prefix the keys and not duplicate with other script in the same server.

Thanks in advance

**Comment by leibale** [comment]
something like:
```javascript
const REDIS_PREFIX = 'prefix';

function redisKey(key) {
  return `${REDIS_PREFIX}:${key}`;
}
```

**Comment by wmantly** [comment]
@leibale The removal of the `prefix` option was a terrible idea. I am down grading because of it. Please rethink this and add it back.

**Comment by samypr100** [comment]
@leibale The prefix option was particularly useful when other libraries allowed you to provide a redis client as a substitute for their own (e.g [bulljs](https://github.com/OptimalBits/bull)). Thus, allowing you to prefix those libraries created keys. This implicitly allowed you to namespace their keys as well which normally would not be possible. It's something [ioredis](https://github.com/luin/ioredis#transparent-key-prefixing) support out of the box

**Comment by leibale** [comment]
@samypr100
We've decided to remove this feature because:

```javascript
const PREFIX = 'prefix:';

const client = createClient({
  prefix: PREFIX
});

function scanKeys() {
  for (const key of client.scanIterator('*')) {
    // key is `prefix:${key}`
    await client.get(key); // will run `GET prefix:prefix:${key}` instead of `GET prefix:${key}`
    await client.get(key.substring(PREFIX.length)); // of-course we can remove the prefix, but that's odd
  }
}
```

Regarding bull - here is a quote from the [PATTERNS.md file](https://github.com/OptimalBits/bull/blob/b6d530f72a774be0fd4936ddb4ad9df3b183f4b6/PATTERNS.md#reusing-redis-connections): "do not set a `keyPrefix` on the connection you create, use bull's built-in prefix feature if you need a key prefix"

https://github.com/OptimalBits/bull/blob/16fdbe90a05ae2e2bcb134a550a97dc84dfe573e/lib/queue.js#L140

**Comment by samypr100** [comment]
Fair, thanks for the clarification. I'm lucky that most of my other dependencies take a prefix option at this time, so I'm okay for the time being :)

**Comment by gajus** [comment]
Had to come up with this monstrosity:

```ts
/**
 * https://github.com/redis/node-redis/issues/1657#issuecomment-2873493460
 */
const createRedisDatabaseAssigner = async ({ url }: { url: string }) => {
  const redisMain = (await createClient({
    // We use database 0 as a main database for test run id storage.
    database: 0,
    url,
  }).connect()) as RedisClientType;

  return {
    assignDatabase: async ({ testRunId }: { testRunId: string }) => {
      let assignedDatabase = (await redisMain.get(testRunId))
        ? Number(await redisMain.get(testRunId))
        : null;

      let newAssignedDatabase = false;

      if (!assignedDatabase) {
        const lastDatabase = (await redisMain.get('last-database'))
          ? Number(await redisMain.get('last-database'))
          : 0;

        // By default there are 16 databases (indexed from 0 to 15) and
        // you can navigate between them using select command.
        // Beware that this means that this concurrency control will break
        // if we run more than 16 tests concurrently.
        assignedDatabase = lastDatabase > 14 ? 1 : lastDatabase + 1;

        await redisMain.set('last-database', assignedDatabase);
        await redisMain.set(testRunId, assignedDatabase);

        newAssignedDatabase = true;
      }

      await redisMain.quit();

      const redis = (await createClient({
        database: assignedDatabase,
        url,
      }).connect()) as RedisClientType;

      if (newAssignedDatabase) {
        await redis.flushDb();
      }

      return redis;
    },
  };
};
```

**Comment by SamuelGaona** [comment]
+1

**Comment by magidandrew** [comment]
I switched off of node-redis for [ioredis](https://github.com/redis/ioredis) because of this

Our use case required many processes to talk to the same db, each with isolated keys.

Yes, we lost redis time series support on ioredis, but it solves the massive headache which is to keep all the processes (which don't know about each other) have unique keyspacing

**Comment by gajus** [comment]
Key prefixing is back.

**Comment by mifi** [comment]
yea the option is now called `keyPrefix`, just like in ioredis (but I think it gets ignored for `sendCommand` which is not the case in ioredis)
