### ISSUE TITLE
Subscriptions are not working

### ISSUE THREAD

**Issue by joacub** [NodeRedis/node-redis#1658]
in the new v4 the subscriptions are not workin anymore.
publish never fire the events in the channels
```js
(app: any) => {
    const { key, serialize, deserialize } = config;
    const db = config.uri || config.db;
    const { redisClient } = config;
    // NOTE: message_buffer (redis) and messageBuffer (ioredis) return buffers
    const subscriberEvent = config.subscriberEvent || 'message';

    if (!redisClient && typeof db !== 'undefined') {
      debug(`Setting up Redis client for db: ${db}`);
    }

    const pub: RedisClientType<any, any> =
      redisClient || redis.createClient({ socket: { url: db } });
    const sub = pub.duplicate();
    sub.connect();

    app.configure(core);
    app.sync = {
      deserialize,
      serialize,
      pub,
      sub,
      type: 'redis',
      ready: new Promise((resolve, reject) => {
        sub.once('ready', resolve);
        sub.once('error', reject);
      }),
    };

    app.on('sync-out', (data: any) => {
      debug(`Publishing key ${key} to Redis`);
      pub.publish(key, data);
    });

    sub.subscribe(key, (message, channel) => {
      console.log(message, channel); // 'message', 'channel'
    });
    sub.on(subscriberEvent, function onSubscriberEvent(e: any, data: any) {
      if (e.toString() === key) {
        debug(`Got ${key} message from Redis`);
        app.emit('sync-in', data);
      }
    });
  };
```

**Comment by puchm** [comment]
I don't know if this helps but if you call the `MONITOR` command on the redis client and add a listener like `redisClient.on('error', () => {...})` that listener will log this:

```
ReplyError: ERR Replica can't interract with the keyspace
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14) {
  command: 'PUBLISH',
  args: [
    'TOPIC',
    'MESSAGE_CONTENT'
  ],
  code: 'ERR'
}
```

Note that this does not get catched by the listener if you don't call `monitor` first for some reason.

**Comment by joacub** [comment]
> Getting the same issue...
> I don't know if this helps but if you enter monitor mode (call the `MONITOR` command) on the redis client and add a listener like `redisClient.on('error', () => {...})` that listener will log this:
> 
> ```
> ReplyError: ERR Replica can't interract with the keyspace
>     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
>     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14) {
>   command: 'PUBLISH',
>   args: [
>     'TOPIC',
>     'MESSAGE_CONTENT'
>   ],
>   code: 'ERR'
> }
> ```
> 
> Note that this does not get catched by the listener if you don't enter monitor mode first.

Yes I got the errors for some reason is acting erratic if not called everything in order.

**Comment by puchm** [comment]
Have you found a solution to this?

**Comment by joacub** [comment]
Yep I have the solution, I will post here soon

**Comment by leibale** [comment]
The PubSub API is a bit different in v4, check the [PubSub section](https://github.com/NodeRedis/node-redis#pubsub) in the README

**Comment by puchm** [comment]
Thank you @leibale !
In fact I was using the way documented in the Readme but I was still on v3. I migrated to v4 now.
