### ISSUE TITLE
Database id isn't supported in v4

### ISSUE THREAD

**Issue by ianberdin** [NodeRedis/node-redis#1659]
### Issue

I'm trying to connect using socket.url with database id:
```ts
const client = createClient({
    legacyMode: false,
    socket: {
      url: 'redis://127.0.0.1:6379/3'
    }
})
```
But it always connects to db=0.

---

### Environment
 - **Node.js Version**: `16`
 - **Redis Server Version**: `6.2.1`
 - **Platform**: `Mac OS 11.6`

**Comment by NovaAtWarren** [comment]
While adding the database ID to the URL may be a good idea, in the meantime you can use `client.SELECT(id)` to select the correct database.
In this case you'd want to use `client.SELECT(3)`.
