### ISSUE TITLE
HSET - ERR wrong number of arguments for 'hset' command

### ISSUE THREAD

**Issue by 7c** [NodeRedis/node-redis#1660]
Node v14.17.6@ubuntu20
Node-Redis 4.0.0-rc.1

`await redis_client.HSET('key', 'field', 'value');`
throws the errror
```
ReplyError: ERR wrong number of arguments for 'hset' command
    at parseError (/opt/api.nxx.org/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/opt/api.xxx.org/node_modules/redis-parser/lib/parser.js:302:14)
```

where

`await redis_client.HSETNX('key', 'field', 'value');`

seems to work. This looks like a bug

**Comment by leibale** [comment]
`HSET` supports updating more than one field at a time, while `HSETNX` does not, that's why their signature is different.
I will add support for the simple case (`client.HSET('key', 'field', 'value')`) to `HSET`, but in the meantime - use one of those options:
```javascript
// object
await client.HSET('key', {field1: '1', field2: '2'});

// map
const map = new Map();
map.set('field1', '1');
map.set('field2', '2');
await client.HSET('key', map);

// tuples
client.HSET('key', [['field1', '1'], ['field2', '2']]);

// flat tuples
client.HSET('key', ['field1', '1', 'field2', '2']);
```

**Comment by jermitval** [comment]
```Javascript
await client.HSET('key', {field1: '1', field2: '2'});
```
still not working, throw same err

**Comment by leibale** [comment]
@jermitval can you please share the error message?

**Comment by jermitval** [comment]
@leibale 

```shell
ReplyError: ERR wrong number of arguments for 'hset' command
    at parseError (d:\project\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (d:\project\node_modules\redis-parser\lib\parser.js:302:14)
```

**Comment by leibale** [comment]
@jermitval what is the redis (not the client, the server) version? less than 4.0?

**Comment by jermitval** [comment]
> @jermitval what is the redis (not the client, the server) version? less than 4.0?

I see, server version is windows 3.2, Thanks!
