### ISSUE TITLE
v4 Doesn't attempt connection to provided IP (always attempts localhost connection)

### ISSUE THREAD

**Issue by cwilliamsonslyp** [NodeRedis/node-redis#1662]
### Issue

I'm trying to connect to an Elasticache cluster from Lambda but I'm receiving connection errors of `Redis client error: Error: connect ECONNREFUSED 127.0.0.1:6379`. It doesn't look like the createClient command is correctly parsing the IP from the url parameter.

This is my first time using redis so it may be a mistake on my part.
```
const { Resolver } = require('dns').promises;
const { createClient } = require("redis");
const resolver = new Resolver();

exports.handler = async event => {
  // writer endpoint in aws console is <redacted>.apse2.cache.amazonaws.com:6379
  const cacheIp = await resolver.resolve4('<redacted>.apse2.cache.amazonaws.com')
  console.log('cacheIp: ', cacheIp)
  const client = createClient({ url: `redis://${cacheIp}:6379` });
  client.on("error", err => console.log("Redis client error: ", err));
  await client.connect();
  
  console.log('after connect');
```
Log Output:
![image](https://user-images.githubusercontent.com/64388493/134416184-a9d4ae4b-eb3c-43e8-a2a0-9dc6383c27d4.png)

![image](https://user-images.githubusercontent.com/64388493/134417482-d16d3f66-891a-4002-9c33-09a96a9f75f3.png)

---

### Environment

Node 14.x Lambda runtime

Elasticache Redis 6.x

Lambda

**Comment by leibale** [comment]
In rc.0 and rc.1 the url is in the socket configuration:
```javascript
createClient({
  socket: {
    url: '...'
  }
});
```

I've already changed it in master, but it wasn't released yet, so from next version you'll need to move it back to:
```javascript
createClient({
  url: '...'
});
```

**Comment by cwilliamsonslyp** [comment]
Thanks @leibale 👍

**Comment by SirCameron** [comment]
Hey, I'm also hitting this error with 4.0.1.
No matter what host I use, it uses localhost.

**Comment by leibale** [comment]
@SirCameron can you please share your code (without sensitive information)?

**Comment by SirCameron** [comment]
Hey @leibale 
I've tried:
```
const redisClient = createClient({
  socket: {
    url: 'redis://redis',
  },
})
redisClient.connect()
```
and 
```
const redisClient = createClient({
  url: 'redis://redis',
})
redisClient.connect()
```
running in a docker container where `redis` is the redis container. I've tried exec-ing into the container and testing the redis connection with redis-cli and all works.
