### ISSUE TITLE
"error" event not emitted on new ReplyError

### ISSUE THREAD

**Issue by emdeevy** [NodeRedis/node-redis#1669]
```
(async () => {
    const client = createClient({username:process.env.redis_username, password:process.env.redis_password});

    client.on('error', (err) => {console.log('Redis Client error', err)});
    client.on('ready', (err) => {console.log('Redis Client ready', err)});
    client.on('connect', (err) => {console.log('Redis Client connect', err)});

    await client.connect();
    const value = await client.get('key');
})();

```

I have this code block, ready and connect logs just fine, but my user does not have permissions for get the key "key", so a ReplyError is returned that I can catch using try catch but the event "error" does not get emitted and 'Redis Client error' never gets logged.

**Comment by leibale** [comment]
The `error` event is fired only for errors in the socket/connection level (such as timeout, unparsable reply, and so on), not a specific command reply.
