### ISSUE TITLE
where is the full-api documentation?

### ISSUE THREAD

**Issue by MadShura** [NodeRedis/node-redis#1670]
i was use getAsync api but its not in redis.
what i was miss ? 
and how to use await with exists api without mak new Promise or use cb function?

v: "redis": "^3.0.2",
such as :

let hasCat = await client.exists('tom')  //already in  a async funciont

console.log(hasCat ) //always true ,not 0 or 1 

thanks. have a good day.

**Comment by MadShura** [comment]
im sorry its just a question not bug. maybe i choose the wrong tag

**Comment by leibale** [comment]
v3 does not support promises "natively", but you can use util.promisify to wrap the cb methods with promise ([see here](https://github.com/NodeRedis/node-redis/tree/v3.1#promises)).
Or, you can upgrade to v4 (still RC, not GA), which supports promises out of the box (but contains a few breaking changes).

**Comment by MadShura** [comment]
yeah i saw that. so i want a api list to make all like promise .
it just wrap the get api.
and what about the getAsync api?

**Comment by leibale** [comment]
v3 is using the ["redis-commands"](https://www.npmjs.com/package/redis-commands) package to add all the commands functions, you can use it to promisify every commands:
```javascript
for (const command of require('redis-comands').list) {
  client[`${command}Async`] = promisify(client[command]).bind(client);
}
```

**Comment by MadShura** [comment]
> v3 is using the ["redis-commands"](https://www.npmjs.com/package/redis-commands) package to add all the commands functions, you can use it to promisify every commands:
> 
> ```js
> for (const command of require('redis-comands').list) {
>   client[`${command}Async`] = promisify(client[command]).bind(client);
> }
> ```

you save my life,thanks again.
