### ISSUE TITLE
Non-zero minimum isolation connection pool size causes infinite function recursion (instant crash)

### ISSUE THREAD

**Issue by EdNutting** [NodeRedis/node-redis#1674]
Hi,

When calling `createClient`, specifying a positive number for the `isolationPoolOptions.min` value causes an infinite recursion through the `RedisClient` constructor. It seems the initial create client calls the constructor, which checks the isolation pool options, which sees there are (say) 3 connections required, so it calls `duplicate` to create them. `duplicate` passes the same isolation options to the new RedisClient, which repeats the same check. Thus, infinite recursion.

I suggest that nested `RedisClient`s created via `duplicate` should be given empty/undefined `isolationPoolOptions`. I think it is also surprising/unintuitive that calling `duplicate` on the top-level redis client would result in an entire new pool being created (i.e. doubling the number of connections) rather than just creating a single new (separate) connection.

**Environment:**
 - **Node.js Version**: 16.4.2
 - **Redis Server Version**: N/A
 - **Node Redis Version**: 4.0.0-rc.2
 - **Platform**: Windows 10

**Comment by leibale** [comment]
I think that `.duplicate()` should be changed to `.duplicate(overrides: Partial<RedisClientOptions>)`, and the `isolationPool.create` function should use that to reset the `isolationPoolOptions` on the "duplicated" connections. What do you think?
