### ISSUE TITLE
Return type is misleading || parsing array type responses is going wrong

### ISSUE THREAD

**Issue by EdNutting** [NodeRedis/node-redis#1675]
Either the return type of `scan` is misleading or the transformer is incorrectly processing the response. If the pattern that is being scanned does not exist, `scan` returns `undefined`. I would expect this to return an empty array not undefined. At any rate, this results in an exception in `scanIterator` because it always expects a valid object and does not handle the undefined case (meaning `reply.cursor` tries to access `cursor` of `undefined`).

https://github.com/NodeRedis/node-redis/blob/d7026f619e66eadb186c15589cb9bc5cc7d03de4/lib/commands/SCAN.ts#L23

I recommend treating empty scans as empty arrays rather than undefined, which seems in keeping with the Redis philosophy.

**Comment by leibale** [comment]
The scan command never returns null, it'll always return an empty array (https://redis.io/commands/scan)

**Comment by EdNutting** [comment]
Currently 6.0.10 but I don't believe the output of scan from Redis has changed recently?

**Comment by georgeben** [comment]
@EdNutting I am facing the same issue. Please how did you resolve the error?
